### ISSUE TITLE
Provider doesn't follow the Files#copy spec

### ISSUE THREAD

**Issue by n3v3rf411** [awslabs/aws-java-nio-spi-for-s3#209]
Files#copy has this spec where copying a directory will result in an empty directory in the target location—and with the entries in the source directory not being copied.

Right now, Files#copy copies all objects inside a location. This is actually handy, but is an element of surprise vs the UnixFileSystem/MacOSXFileSystem.

> Copy a file to a target file.
> 
> This method copies a file to the target file with the options parameter specifying how the copy is performed. By default, the copy fails if the target file already exists or is a symbolic link, except if the source and target are the same file, in which case the method completes without copying the file. File attributes are not required to be copied to the target file. If symbolic links are supported, and the file is a symbolic link, then the final target of the link is copied. If the file is a directory then it creates an empty directory in the target location (entries in the directory are not copied). This method can be used with the walkFileTree method to copy a directory and all entries in the directory, or an entire file-tree where required.
>

**Comment by markjschreiber** [comment]
Interesting. Arguably the "standard" behavior is the more surprising (at leas to me).  

I'd be open to a PR that would bring us closer to the "normal" behavior or alternatively we could document in the README that we differ here.

One problem with the standard recommendation to use the `walkFileTree` method to copy the entries in the directory is that this is much more expensive in S3 due to the large number of API calls that are involved (both time and financially expensive). This would tend to make me favor having copy also copy the files underneath.

**Comment by markjschreiber** [comment]
Documented our difference and the reasons for this (mainly having to do this by walking the tree would be way too inefficient.)
