### ISSUE TITLE
`Files/deleteIfExists` always returns true

### ISSUE THREAD

**Issue by onetom** [awslabs/aws-java-nio-spi-for-s3#210]
The `FileSystemProvider#deleteIfExists` has a default implementation:
https://github.com/openjdk/jdk/blob/e3c6cf8eaf931d9eb46b429a5ba8d3bbded3728a/src/java.base/share/classes/java/nio/file/spi/FileSystemProvider.java#L774-L807

It depends on the `FileSystemProvider#delete` method and expects it to throw, if the file-to-be-deleted does not exist.
This default implementation is not overridden by `S3FileSystemProvider` though and the `delete` method does NOT seem to check for the file's existence.

The underlying https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html operation doesn't seem to return any indication of whether the deletion succeeded or not, so it's not possible to implement precise `deleteIfExists` semantics for S3.

`deleteIfExists` could indicate this problem by always throwing some "Unsupported operation" exception, BUT that's less friendly than the current behaviour, which allows writing file system agnostic application code.

I thought of using `S3FileSystemProvider#exists` to approximate the semantics of `deleteIfExists`, but since that wouldn't be an atomic operation, it wouldn't be a precise implementation either, plus it would incur an extra REST API roundtrip to S3.

Either way, it would worth mentioning in the `README.md` at least, that `deleteIfExists` always returns `true` and why, so others wouldn't have to wonder or dig deep, like I did.

**Comment by markjschreiber** [comment]
Apology for the delay

I can see two options. Make an exists call followed by a delete call and document the method to indicate that it isn't atomic, or document that it is effectively delete.

I mostly prefer the former as S3 only ever guarantees read after right consistency so that caveat will really apply to every call (and something we should probably call out in the main README).

Would love to see a PR if you are willing to contribute one.

**Comment by markjschreiber** [comment]
Updated README.md to clarify the current behaviour
