### ISSUE TITLE
Special characters handling when converting between URI and Path

### ISSUE THREAD

**Issue by thsandu** [awslabs/aws-java-nio-spi-for-s3#241]
There seem to be issues with the decoding of special characters of file paths when using the URI. Specifically when we want to get again the Path from the URI, the encoding seems not to be decoded again. See this changed test here: https://github.com/thsandu/aws-java-nio-spi-for-s3-issues-with-s3x/blob/dcae76d542bf0b5b4047e10c680d5f7c1c6dc33a/src/test/java/software/amazon/nio/spi/s3/S3PathTest.java#L365

Addition:
```
assertEquals(withSpecialChars, Paths.get(withSpecialChars.toUri()));
```
This yields:
```
Expected :dir with space/and	special&chars
Actual   :/dir+with+space/and	special&chars
```

**Comment by markjschreiber** [comment]
The problem exists because the S3 "URIs" are not strictly URIs because the don't URL encode special characters. Unfortunately the Java NIO spec requires that URIs be instances of the Java URI which will URL encode. The upshot of this is that there is really no mechanism for this library to support S3 URIs that are not actually valid. It is made even more complicated because S3 URIs can contain the `%` character so it's difficult to distinguish between encoded and not encoded.

Minimally the TODO here is to document this limitation in the README.md.

I'm not certain a fix is possible but let me know if you see a path to a solution.

**Comment by markjschreiber** [comment]
Update documentation to reflect that there are cases where an S3 URI is not a true URI but that Java uses URIs in NIO and these must be valid.
