### ISSUE TITLE
S3FileSystem.getRootDirectories() returning an empty list

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#35]
I think this is accordingly with the design choice of 1:1 between bucket and FS.
I am wondering if we could relax/review this choice to make an endpoint a FS and each bucket a root file system. IMHO this would be a more natural approach making the buckets discoverable:

```
FileSystem s3 = FileSystems.newFileSystem(...);
for (Path root : s3.getRootDirectories()) {
  do_something(root);
}
```

**Comment by markjschreiber** [comment]
This is one area where S3 doesn't match a filesystem well. I did play with having the root of the filesystem "contain" buckets that you can list but there are lots of edge cases. 

1. You need to have the ListBuckets IAM permission.
2. There are many more buckets that you can access (public buckets, cross account shared buckets etc) than you can list with a call to ListBuckets, so you end up with an S3 "filesystem" which has a partial root. 
2. Related to the above. For historical reasons, buckets have a global namespace, even though they ultimately live in a partition (AWS, gov-cloud(s), AWS-cn etc), a Region and an account. This means all buckets could be thought of as living in a universal file system but in many ways this isn't a useful abstraction anymore. 
3. Buckets can have quite different requirements for a `client` due to things like regional endpoints, accelerated endpoints, different encryption key types and properties. 
4. In POSIX and windows filesystem root directories are not very different from a directory but buckets are substantially different from a directory and potentially from one another. This only becomes increasingly more true as S3 gains more features. 

None of this is to say you couldn't do this differently. For example FSx for Lustre does allow you to map multiple buckets to locations on the drive but does still require specific mappings of named buckets. You still can't browse everything unless you map all your buckets.

**Comment by stefanofornari** [comment]
Thanks for the explanation, it makes sense. What about returning "/" like posix file systems? It would be more consistent and it'd provide a starting point for descending the tree.

**Comment by markjschreiber** [comment]
I think we already do do that. Where "/" is the root of the bucket

https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/main/src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java#L183-L186

**Comment by stefanofornari** [comment]
That's strange... can you try this snippet:

```
FileSystem fs = FileSystems.newFileSystem(...);
for (Path root : s3.getRootDirectories()) {
    System.out.println(root);
}
```

I do not get anything (although I can see the call to getRootDirectories()

**Comment by markjschreiber** [comment]
Turns out the method was returning the root `Path` rather than an `Iterarable` containing the root `Path`. It compiled because `Path` is itself `Iterable`.
