### ISSUE TITLE
"write operations are not currently supported, please file a feature request with your use case"

### ISSUE THREAD

**Issue by yelhouti** [awslabs/aws-java-nio-spi-for-s3#4]
Hi there,

Great library you have here, sadly it only works for read access. Do you have any plans to support write access ?

Thanks in advance.

**Comment by oeph** [comment]
just for the sake of completeness: this was the discussion at the official java sdk repo https://github.com/aws/aws-sdk-java-v2/issues/1388#issuecomment-1381389190

**Comment by markjschreiber** [comment]
It's great to see people wanting some kind of write support. To support writes, we would need to implement `java.nio.channels.WritableByteChannel` and maybe `java.nio.channels.GatheringByteChannel`.

We could alter the `S3SeekableByteChannel` to implement the `write` and `truncate` calls by delegating to one or more implementations of the above. There are some complications though. S3 doesn't allow random writes so if you attempted to write when the position of the channel was not 0 it would have to fail. This might be OK for some use cases but doesn't generalize well. Pseudo support for random writes could be done if we buffer the writes in memory or in temp files and then only perform the actual write when the channel is closed. For other users of S3 this will be read-after-write consistent. E.g. another S3 client will not see the changes until they are fully written to S3 (which is normal for S3). We could allow consistent reads for a `S3SeekableByteChannel` so that users of that channel see all updates immediately. Harder to implement but probably more what people would expect.

Let me know your thoughts.

**Comment by oeph** [comment]
Would you be up to implement this? I have to say im not an expert, but could try to assist, test, ...

> Pseudo support for random writes could be done if we buffer the writes in memory or in temp files and then only perform the actual write when the channel is closed

Should probably be written to a temp file instead of memory, in order to also support use cases where large files are handled.

> Harder to implement but probably more what people would expect.

True, that could get complicated, but would make sense to do for sure.

**Comment by markjschreiber** [comment]
I can do it but it will certainly be a secondary (perhaps even tertiary) activity.  What kind of time frame are you on? What is your most frequent use case?

**Comment by oeph** [comment]
We are currently trying to get our systems ready and would love to integrate this library sometime around March/April. At least this is the current plan.

For us the most common use case is reading, however we also need to write files, and the file size can vary greatly.
It could range from files of some few megabytes to files of multiple gigabytes.

**Comment by oeph** [comment]
@markjschreiber we got a request to finish this integration sooner than expected. I will try to open a PR in the next days.

**Comment by markjschreiber** [comment]
That would be awesome

**Comment by oeph** [comment]
@markjschreiber as you mentioned, its hard to support read and write at the same time. How about having the channel only either support read or write? I think this is the approach Azure is going for with their NIO implementation.

**Comment by markjschreiber** [comment]
I agree, this is probably the way to go. This also allows different channel implementations that specialize in different approaches to writing if needed. In the same way we can use different read channels like one that specializes in aggressive read ahead caching or one that only reads specifically what is requested.

**Comment by oeph** [comment]
#5 closes this ticket
