### ISSUE TITLE
Configurable copy timeouts

### ISSUE THREAD

**Issue by n3v3rf411** [awslabs/aws-java-nio-spi-for-s3#513]
I'm copying multiple 1GB files across buckets in different regions and they timeout after the fixed 1 minute timeout that's set in TimeOutUtils.

Can this be made configurable?

**Comment by markjschreiber** [comment]
This seems reasonable. We have some other configurations processed in https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/main/src/main/java/software/amazon/nio/spi/s3/config/S3NioSpiConfiguration.java so this could be added there.

Most of the Async API calls in the library have time outs. To keep the number of configurable time outs reasonably small we might want to have two sets. One for information/ metadata type requests which should have short time outs and one for read/write operations which may need long time outs.

If you have some code in mind I would be happy to review a PR.

**Comment by kartavyashankar** [comment]
Hi @markjschreiber . I wanted to know if I could contribute on this.
Are there any pre-requisites for contributing to this project?

**Comment by markjschreiber** [comment]
> Hi @markjschreiber . I wanted to know if I could contribute on this. Are there any pre-requisites for contributing to this project?

Sure, take a look at the README.md along with the CONTRIBUTING.md and code of conduct.

**Comment by kartavyashankar** [comment]
Thanks @markjschreiber ,
Also it would be very helpful to know if there is a deadline or an expected due date for this issue.

**Comment by markjschreiber** [comment]
No timeline at present - sooner is always better ;)

**Comment by kartavyashankar** [comment]
Sure, I will try to complete this as soon as I can

**Comment by kartavyashankar** [comment]
Hi @markjschreiber , G'Day
I can see that TimeOutUtils has 3 timeouts configured (1 minute, 3 minutes and 5 minutes).
In most places, we have a timeout of 1 minute.

Since you mentioned that we can have two sets of timeouts. One for information/ metadata type requests which should have short time outs, I am keeping these requests as is.

For the other set, read/write operations which may need long time outs,  do you have a number in mind or can I configure these operations to one of pre-configured values (3 or 5 minutes)?

Thanks

**Comment by markjschreiber** [comment]
You could probably make them all configurable (short, medium and long) with defaults of 1, 3 and 5 minutes.
